image: node:11.3-stretch

variables:
  REGISTRY_NAME: 'registry.gitlab.com'
  IMAGE_NAME: "registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

stages:
  - test
  - build

# test:
#  # install deps
#  before_script:
#    - yarn
#   tags:
#     - docker
#   services:
#     - mongo
#     - redis:latest
#   variables:
#     MONGO_URI: "mongodb://mongo"
#     REDIS_URI: "redis://redis"
#   stage: test
#   script:
#     - yarn test

build:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  # only:
  #   - master
  #   - tags
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${REGISTRY_NAME}
    - docker build . -t ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}
