image: node:lts

variables:
  REGISTRY_NAME: 'registry.gitlab.com'
  IMAGE_NAME: "registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

stages:
  - test
  - build

test:
  # install deps
  before_script:
    - yarn
  tags:
    - docker
  services:
    - postgres:latest
    - redis:latest
  variables:
    PG_URI: "postgresql://runner@postgres"
    REDIS_URI: "redis://redis"
    PG_DBNAME: "test_uexky"
    POSTGRES_DB: test_uexky
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
  stage: test
  script:
    - yarn test models/config.test

build:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
    - tags
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${REGISTRY_NAME}
    - docker build . -t ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}
