// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"gitlab.com/abyss.club/uexky/auth"
	"gitlab.com/abyss.club/uexky/graph"
	"gitlab.com/abyss.club/uexky/lib/mail"
	"gitlab.com/abyss.club/uexky/lib/postgres"
	"gitlab.com/abyss.club/uexky/lib/redis"
	"gitlab.com/abyss.club/uexky/uexky"
	"gitlab.com/abyss.club/uexky/uexky/repo"
)

// Injectors from wire.go:

func InitProdServer() (*Server, error) {
	client, err := redis.NewClient()
	if err != nil {
		return nil, err
	}
	authRepo := &auth.Repo{
		Redis: client,
	}
	adapter := mail.NewAdapter()
	service := &auth.Service{
		Repo: authRepo,
		Mail: adapter,
	}
	db, err := postgres.NewDB()
	if err != nil {
		return nil, err
	}
	txAdapter := &postgres.TxAdapter{
		DB: db,
	}
	entityRepo := repo.NewRepo(client)
	uexkyService, err := uexky.NewService(txAdapter, entityRepo)
	if err != nil {
		return nil, err
	}
	resolver := &graph.Resolver{
		Auth:  service,
		Uexky: uexkyService,
	}
	server := &Server{
		Resolver:  resolver,
		TxAdapter: txAdapter,
	}
	return server, nil
}
