// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"gitlab.com/abyss.club/uexky/graph"
	"gitlab.com/abyss.club/uexky/lib/mail"
	"gitlab.com/abyss.club/uexky/lib/postgres"
	"gitlab.com/abyss.club/uexky/lib/redis"
	"gitlab.com/abyss.club/uexky/repo"
	"gitlab.com/abyss.club/uexky/uexky"
	"gitlab.com/abyss.club/uexky/uexky/entity"
)

// Injectors from wire.go:

func InitProdServer() (*Server, error) {
	client, err := redis.NewClient()
	if err != nil {
		return nil, err
	}
	forumRepo := &repo.ForumRepo{}
	userRepo := &repo.UserRepo{
		Redis: client,
		Forum: forumRepo,
	}
	adapter := mail.NewAdapter()
	userService := &entity.UserService{
		Repo: userRepo,
		Mail: adapter,
	}
	forumService := &entity.ForumService{
		Repo: forumRepo,
	}
	notiRepo := &repo.NotiRepo{}
	notiService := &entity.NotiService{
		Repo: notiRepo,
	}
	db, err := postgres.NewDB()
	if err != nil {
		return nil, err
	}
	txAdapter := &postgres.TxAdapter{
		DB: db,
	}
	service := &uexky.Service{
		User:      userService,
		Forum:     forumService,
		Noti:      notiService,
		TxAdapter: txAdapter,
	}
	resolver := &graph.Resolver{
		Service: service,
	}
	server := &Server{
		Resolver:  resolver,
		Service:   service,
		TxAdapter: txAdapter,
	}
	return server, nil
}
