// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"gitlab.com/abyss.club/uexky/graph"
	"gitlab.com/abyss.club/uexky/repo"
	"gitlab.com/abyss.club/uexky/service"
)

// Injectors from wire.go:

func InitResolver() graph.Resolver {
	repository := repo.NewRepository()
	serviceService := service.NewService(repository)
	resolver := graph.NewResolver(serviceService)
	return resolver
}
