extend type Query {
  """ The count of unread notifications. """
  unreadNotiCount: Int!
  """ Notifications for current user. """
  notification(query: SliceQuery!): NotiSlice!
}

enum NotiType {
  system
  replied
  quoted
}

""" NotiSlice object is for selecting specific 'slice' of an object to return.
Affects the returning SliceInfo. """
type NotiSlice {
  notifications: [Notification!]!
  sliceInfo: SliceInfo!
}

type Notification {
  """ Type of Notification. "system", "replied" or "quoted"."""
  type: NotiType!
  """ Time when a notify event triggers. E.g. The time when a system event is
  announced from the server."""
  eventTime: Time!
  """ The notification is read or not."""
  hasRead: Boolean!
  """ notification content for different type."""
  content: NotiContent!
}

""" Union type of Notificatiion contents """
union NotiContent = SystemNoti | RepliedNoti | QuotedNoti

""" Object describing contents of a system notification."""
type SystemNoti {
  """ Notification title."""
  title: String!
  """ Markdown formatted notification content."""
  content: String!
}

""" Stripped version of Thread object."""
type ThreadOutline {
  id: UID!
  title: String
  """ Markdown formatted content."""
  content: String!
  mainTag: String!
  subTags: [String!]!
}

""" Stripped version of Post object."""
type PostOutline {
  id: UID!
  """ Name if not anonymous, anonymous ID otherwise."""
  author: String!
  """ Markdown formatted content."""
  content: String!
}

""" Object describing contents of a replied notification."""
type RepliedNoti {
  """ The Thread object that is replied."""
  thread: ThreadOutline!
  """ How much new replies since the last read of this notification."""
  newRepliesCount: Int!
  """ ID of the first reply since the last read of this notification."""
  firstReplyId: UID!
}

""" Object describing contents of a quoted notification."""
type QuotedNoti {
  """ ID of the Thread quoted."""
  threadId: UID!
  """ The Post object quoted."""
  quotedPost: PostOutline!
  """ The Post object that made this notification."""
  post: PostOutline!
}
