queries = '''
    # The count of unread notifications.
    unreadNotiCount(): UnreadNotiCount!
    # Notifications for current user.
    notification(type: String!, query: SliceQuery!): NotiSlice!
'''

types = '''
# Count of different types of unread notifications.
type UnreadNotiCount {
    # Announcement messages from server.
    system: Int!
    # Threads that are replied.
    replied: Int!
    # Posts that are referred.
    refered: Int!
}

# NotiSlice object is for selecting specific 'slice' of an object to return. Affects returned SliceInfo.
type NotiSlice {
    # Announcement messages from server.
    system: [SystemNoti!]
    # Threads that are replied.
    replied: [RepliedNoti!]
    # Posts that are referred.
    refered: [ReferedNoti!]
    # SliceInfo objects are generated by the server. Can be used in consecutive queries.
    sliceInfo: SliceInfo!
}

# Object describing a system notification.
type SystemNoti {
    # ID contains different types of format.
    id: String!
    # Type of Notification. "system", "replied" or "referred".
    type: String!
    # Time when a notify event triggers. E.g. The time when a system event is announced from the server.
    eventTime: Time!
    # The nofitication is read or not.
    hasRead: Boolean!
    # Notification title.
    title: String!
    # Notification content.
    content: String!
}

# Object describing a replied notification.
type RepliedNoti {
    # ID contains different types of format.
    id: String!
    # Type of Notification. "system", "replied" or "referred".
    type: String!
    # Time when a notify event triggers. E.g. The time when a thread is replied.
    eventTime: Time!
    # The nofitication is read or not.
    hasRead: Boolean!
    # The thread object that is replied.
    thread: Thread!
    # Array of users that replied. Same as the corresponding author field in the object "Post".
    repliers: [String!]!
}

# Object describing a referred notification.
type ReferedNoti {
    # ID contains different types of format.
    id: String!
    # Type of Notification. "system", "replied" or "referred".
    type: String!
    # Time when a notify event triggers. E.g. The time when a post is referred.
    eventTime: Time!
    hasRead: Boolean!
    # The thread object that is referred in.
    thread: Thread!
    # The post object that is referred.
    post: Post!
    # Array of users that referred the post. Same as the corresponding author field in the object "Post".
    referers: [String!]!
}
'''
