extend type Query {
  """ Main Tags."""
  mainTags: [String!]!
  """ Tags that are recommended."""
  recommended: [String!]!
  """ Searching tags by keyword."""
  tags(
    """ Search keyword."""
    query: String,
    """ Amount of tags returned."""
    limit: Int,
  ): [Tag!]!
}

type Tag {
  """ Name of tag."""
  name: String!
  """ The tag is a MainTag if true, SubTag otherwise."""
  isMain: Boolean!
}
