// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"gitlab.com/abyss.club/uexky/graph"
	"gitlab.com/abyss.club/uexky/server"
	"gitlab.com/abyss.club/uexky/uexky"
	"gitlab.com/abyss.club/uexky/uexky/entity"
)

// Injectors from wire.go:

func InitServer() *server.Server {
	userService := &entity.UserService{}
	forumService := &entity.ForumService{}
	notiService := &entity.NotiService{}
	service := &uexky.Service{
		User:  userService,
		Forum: forumService,
		Noti:  notiService,
	}
	resolver := &graph.Resolver{
		Service: service,
	}
	serverServer := &server.Server{
		Resolver: resolver,
	}
	return serverServer
}
