// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package entity

import (
	"time"
)

type NotiSlice struct {
	System    []*SystemNoti  `json:"system"`
	Replied   []*RepliedNoti `json:"replied"`
	Quoted    []*QuotedNoti  `json:"quoted"`
	SliceInfo *SliceInfo     `json:"sliceInfo"`
}

type PostInput struct {
	ThreadID  string   `json:"threadId"`
	Anonymous bool     `json:"anonymous"`
	Content   string   `json:"content"`
	QuoteIds  []string `json:"quoteIds"`
}

type PostSlice struct {
	Posts     []*Post    `json:"posts"`
	SliceInfo *SliceInfo `json:"sliceInfo"`
}

type SliceInfo struct {
	FirstCursor string `json:"firstCursor"`
	LastCursor  string `json:"lastCursor"`
	HasNext     bool   `json:"hasNext"`
}

type SliceQuery struct {
	Before *string `json:"before"`
	After  *string `json:"after"`
	Limit  int     `json:"limit"`
}

type ThreadCatalogItem struct {
	PostID    string    `json:"postId"`
	CreatedAt time.Time `json:"createdAt"`
}

type ThreadInput struct {
	Anonymous bool     `json:"anonymous"`
	Content   string   `json:"content"`
	MainTag   string   `json:"mainTag"`
	SubTags   []string `json:"subTags"`
	Title     *string  `json:"title"`
}

type ThreadSlice struct {
	Threads   []*Thread  `json:"threads"`
	SliceInfo *SliceInfo `json:"sliceInfo"`
}

type UnreadNotiCount struct {
	System  int `json:"system"`
	Replied int `json:"replied"`
	Quoted  int `json:"quoted"`
}
