schema {
    query: Query
    mutation: Mutation
}

type Query {
    account(): Account!
    threadSlice(limit: Int! tags: [String!] after: String!): ThreadSlice!
    thread(id: String!): Thread!
}

type Mutation {
    addAccount(): Account!
    addName(name: String!): Account!
    pubThread(new: NewThread!): Thread!
    pubPost(new: NewPost!): Post!
}

type SliceInfo {
    firstCursor: String!
    lastCursor: String!
}

scalar Time

// Data Type Defines
type Account {
    token: String!
    names: [String!]
}

type NewThread {
    name: String
    content: String!
    mainTag: String!
    subTag: [String]
    title: String
}

type Thread {
    id: String!
    anonymous: Boolean!
    author: String!
    content: String!
    createTime: Time!

    mainTag: String!
    subTags: [String!]
    title: String
    replies(limit: Int! after: String): PostSlice!
}

type ThreadSlice {
  threads: [Thread]!
  sliceInfo: SliceInfo!
}


type NewPost {
    name: String
    content: String!
    refers: [String!]
}

type Post {
    id: String!
    anonymous: Boolean!
    author: String!
    content: String!
    createTime: Time!

    refers: [Post!]
}

type PostSlice {
  posts: [Post]!
  sliceInfo: SliceInfo!
}
